### ISSUE TITLE
Plans for haptic feedback & more advanced DualSense features?

### ISSUE THREAD

**Issue by FlooferLand** [radu781/dualsense-rs#1]
I recognise this project is still new, but I wonder what you plan on implementing and plan not to implement.

The DualSense lacks PC support everywhere, even in the C++ library space, so it'd be nice to see this crate get more features.

**Comment by radu781** [comment]
I am currently taking a break from this project but I will return in 2 weeks' time. I am planning to add most of, if not all features of the dualsense controller to this library. I will consider prioritising the trigger buttons vibration for my next changes.
Thanks for the input!

**Comment by radu781** [comment]
Sorry for the delay. I will create a pull request to implement this issue's requirements (trigger button vibration effect). So far reading the values works, but setting the thresholds and vibration patterns needs work. I will address this during this week.

**Comment by radu781** [comment]
Added the requested functionalities in 5e2aeb455bf148a246b8d069fa343a1af4f9067f, did not create a pull request to address only this issue because it was difficult to separate the needed changes. Thanks again for the interest in this project!
